# Generated by Django 4.1.6 on 2023-02-13 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Brand Nomi')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ombor Nomi')),
                ('warehouse_size', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tovar Nomi')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Sigimi')),
                ('product_size', models.FloatField(blank=True, null=True)),
                ('box_weight', models.FloatField(blank=True, null=True)),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Kodi')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
            ],
        ),
        migrations.CreateModel(
            name='InProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateTimeField(verbose_name='Sana')),
                ('quantity', models.IntegerField(verbose_name='Soni')),
                ('body_price', models.IntegerField(verbose_name='Tannarxi')),
                ('body_summa', models.IntegerField(verbose_name='TanSumma')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('summa', models.IntegerField(verbose_name='Summa')),
                ('shop_price', models.IntegerField(verbose_name='Snarxi')),
                ('shop_summa', models.IntegerField(verbose_name='Ssumma')),
                ('comment', models.TextField(blank=True, default='Tovar kirimi')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_provider', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warehouse')),
            ],
        ),
    ]
