# Generated by Django 4.1.6 on 2023-02-18 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_rename_box_weight_product_product_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inproduct',
            name='comment',
            field=models.TextField(blank=True, default='Tovar kirimi', null=True),
        ),
        migrations.CreateModel(
            name='OutProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_date', models.DateTimeField(verbose_name='Sana')),
                ('quantity', models.IntegerField(verbose_name='Soni')),
                ('body_price', models.IntegerField(verbose_name='Tannarxi')),
                ('body_summa', models.IntegerField(verbose_name='TanSumma')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('summa', models.IntegerField(verbose_name='Summa')),
                ('shop_price', models.IntegerField(verbose_name='Snarxi')),
                ('shop_summa', models.IntegerField(verbose_name='Ssumma')),
                ('profit', models.IntegerField(verbose_name='Foyda')),
                ('sprofit', models.IntegerField(verbose_name='Sfoyda')),
                ('comment', models.TextField(blank=True, default='Tovar chiqimi', null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_seller', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warehouse')),
            ],
        ),
    ]
