# Generated by Django 4.1.6 on 2023-02-20 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_product_about_alter_inproduct_comment_outproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outproduct',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'CL'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outproduct',
            name='trader',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'PR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
