# Generated by Django 4.1.6 on 2023-02-20 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_outproduct_client_alter_outproduct_trader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inproduct',
            name='provider',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'PR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_provider', to=settings.AUTH_USER_MODEL),
        ),
    ]
