# Generated by Django 4.1.6 on 2023-02-27 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_inproduct_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inproduct',
            options={'ordering': ['-in_date']},
        ),
        migrations.AlterModelOptions(
            name='outproduct',
            options={'ordering': ['-out_date']},
        ),
        migrations.RemoveField(
            model_name='outproduct',
            name='client',
        ),
        migrations.RemoveField(
            model_name='outproduct',
            name='shop_price',
        ),
        migrations.RemoveField(
            model_name='outproduct',
            name='shop_summa',
        ),
        migrations.RemoveField(
            model_name='outproduct',
            name='sprofit',
        ),
        migrations.AlterField(
            model_name='outproduct',
            name='trader',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'PR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OutProductB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_date', models.DateTimeField(verbose_name='Sana')),
                ('quantity', models.IntegerField(verbose_name='Soni')),
                ('body_price', models.IntegerField(verbose_name='Tannarxi')),
                ('body_summa', models.IntegerField(verbose_name='TanSumma')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('summa', models.IntegerField(verbose_name='Summa')),
                ('shop_price', models.IntegerField(verbose_name='Snarxi')),
                ('shop_summa', models.IntegerField(verbose_name='Ssumma')),
                ('profit', models.IntegerField(verbose_name='Foyda')),
                ('sprofit', models.IntegerField(verbose_name='Sfoyda')),
                ('comment', models.TextField(blank=True, default='Tovar chiqimi B', null=True)),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'CL'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('trader', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'PR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_seller', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warehouse')),
            ],
            options={
                'ordering': ['-out_date'],
            },
        ),
    ]
