# Generated by Django 4.1.6 on 2023-02-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_inproduct_options_alter_outproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Narxi'),
        ),
        migrations.AddField(
            model_name='product',
            name='s_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Snarxi'),
        ),
    ]
