# Generated by Django 4.1.6 on 2023-02-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_price_product_s_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ombor Nomi')),
                ('warehouse_size', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['product']},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='name',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='warehouse_size',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='body_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tannarxi'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='body_summa',
            field=models.IntegerField(blank=True, null=True, verbose_name='TanSumma'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='comment',
            field=models.TextField(blank=True, default='Tovar kirimi', null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sana'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Narxi'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Soni'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shop_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Snarxi'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shop_summa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ssumma'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='summa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Summa'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warehousename'),
        ),
        migrations.AlterField(
            model_name='inproduct',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warehousename'),
        ),
        migrations.AlterField(
            model_name='outproduct',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warehousename'),
        ),
        migrations.AlterField(
            model_name='outproductb',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warehousename'),
        ),
    ]
