# Generated by Django 4.1.6 on 2023-02-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_warehouse_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inproduct',
            name='event_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
