# Generated by Django 4.1.6 on 2023-02-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_inproduct_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='event_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
