# Generated by Django 4.1.6 on 2023-03-07 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_outproduct_event_id_outproductb_event_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inproduct',
            options={},
        ),
        migrations.RemoveField(
            model_name='inproduct',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='inproduct',
            name='in_date',
        ),
        migrations.RemoveField(
            model_name='inproduct',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='inproduct',
            name='warehouse',
        ),
        migrations.CreateModel(
            name='InDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('in_date', models.DateTimeField(verbose_name='Sana')),
                ('comment', models.TextField(blank=True, default='Tovar kirimi', null=True)),
                ('provider', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'PR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_provider', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warehousename')),
            ],
            options={
                'ordering': ['-in_date'],
            },
        ),
        migrations.AddField(
            model_name='inproduct',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.indocument'),
        ),
    ]
