# Generated by Django 4.1.6 on 2023-03-07 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_alter_inproduct_options_remove_inproduct_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='outproductb',
            options={},
        ),
        migrations.RemoveField(
            model_name='outproduct',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='outproduct',
            name='out_date',
        ),
        migrations.RemoveField(
            model_name='outproduct',
            name='trader',
        ),
        migrations.RemoveField(
            model_name='outproduct',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='outproductb',
            name='client',
        ),
        migrations.RemoveField(
            model_name='outproductb',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='outproductb',
            name='out_date',
        ),
        migrations.RemoveField(
            model_name='outproductb',
            name='trader',
        ),
        migrations.RemoveField(
            model_name='outproductb',
            name='warehouse',
        ),
        migrations.CreateModel(
            name='OutDocumentClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('out_date', models.DateTimeField(verbose_name='Sana')),
                ('comment', models.TextField(blank=True, default='Tovar chiqimi B', null=True)),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'CL'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper', to=settings.AUTH_USER_MODEL)),
                ('trader', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'PR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_seller', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warehousename')),
            ],
            options={
                'ordering': ['-out_date'],
            },
        ),
        migrations.CreateModel(
            name='OutDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('out_date', models.DateTimeField(verbose_name='Sana')),
                ('comment', models.TextField(blank=True, default='Tovar chiqimi', null=True)),
                ('trader', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'PR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.warehousename')),
            ],
            options={
                'ordering': ['-out_date'],
            },
        ),
        migrations.AddField(
            model_name='outproduct',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.outdocument'),
        ),
        migrations.AddField(
            model_name='outproductb',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.outdocumentclient'),
        ),
    ]
