# Generated by Django 4.1.6 on 2023-03-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_outproduct_options_alter_outproductb_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indocument',
            name='summa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Summa'),
        ),
    ]
