# Generated by Django 4.1.6 on 2023-03-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_indocument_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indocument',
            name='summa',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Summa'),
        ),
    ]
