# Generated by Django 4.1.6 on 2023-03-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_outdocument_summa_outdocumentclient_ssumma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outdocument',
            name='profit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Foyda'),
        ),
        migrations.AddField(
            model_name='outdocumentclient',
            name='profit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Foyda'),
        ),
        migrations.AddField(
            model_name='outdocumentclient',
            name='sprofit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sfoyda'),
        ),
    ]
