# Generated by Django 4.1.6 on 2023-02-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PR', 'Provider'), ('CL', 'Client')], default='PR', max_length=50),
        ),
    ]
