# Generated by Django 4.1.6 on 2023-02-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0002_incash'),
    ]

    operations = [
        migrations.AddField(
            model_name='incash',
            name='summa',
            field=models.IntegerField(null=True),
        ),
    ]
