# Generated by Django 4.1.6 on 2023-02-22 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashes', '0003_incash_summa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incash',
            name='client',
        ),
        migrations.CreateModel(
            name='InCashClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateTimeField(verbose_name='Sana')),
                ('summa', models.IntegerField(null=True)),
                ('comment', models.TextField(blank=True, default='Pul kirimi client', null=True)),
                ('cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashes.cash')),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'CL'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_payer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
