# Generated by Django 4.1.6 on 2023-02-22 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashes', '0005_remove_incashclient_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_date', models.DateTimeField(verbose_name='Sana')),
                ('summa', models.IntegerField(null=True)),
                ('comment', models.TextField(blank=True, default='Pul chiqimi', null=True)),
                ('cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashes.cash')),
                ('trader', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'PR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
