# Generated by Django 4.1.6 on 2023-02-23 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0006_outcash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Sana')),
                ('summa', models.IntegerField(null=True)),
                ('comment', models.TextField(blank=True, default='Xarajat', null=True)),
                ('cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashes.cash')),
            ],
        ),
    ]
