# Generated by Django 4.1.6 on 2023-02-26 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashes', '0007_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('event_id', models.CharField(blank=True, max_length=20, null=True)),
                ('trans_date', models.CharField(blank=True, max_length=255, null=True)),
                ('cash_summa', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('cash_ssumma', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('body_summa', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='TransTanSumma')),
                ('summa', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='TransSumma')),
                ('shop_summa', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='TransSSumma')),
                ('comment', models.TextField(blank=True, null=True)),
                ('cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_cash', to='cashes.cash')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_client', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_provider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
