# Generated by Django 4.1.6 on 2023-02-26 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashes', '0008_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'CL'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'PR'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_provider', to=settings.AUTH_USER_MODEL),
        ),
    ]
