# Generated by Django 4.1.6 on 2023-02-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0009_alter_transaction_client_alter_transaction_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='incash',
            options={'ordering': ['-in_date']},
        ),
        migrations.AlterModelOptions(
            name='incashclient',
            options={'ordering': ['-in_date']},
        ),
        migrations.AlterModelOptions(
            name='outcash',
            options={'ordering': ['-out_date']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-trans_date']},
        ),
        migrations.RenameField(
            model_name='incashclient',
            old_name='summa',
            new_name='ssumma',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shop_summa',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name='TransSSumma'),
        ),
    ]
