# Generated by Django 4.1.6 on 2023-02-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0010_alter_expense_options_alter_incash_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sprofit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
