# Generated by Django 4.1.6 on 2023-02-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0011_transaction_profit_transaction_sprofit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cash_ssumma',
        ),
    ]
