# Generated by Django 4.1.6 on 2023-02-28 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0013_rename_shop_summa_transaction_ssumma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='event_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='incash',
            name='event_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='incashclient',
            name='event_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='outcash',
            name='event_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='event_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
