# Generated by Django 4.1.6 on 2023-03-03 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashes', '0014_expense_event_id_incash_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutCashClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('out_date', models.DateTimeField(verbose_name='Sana')),
                ('ssumma', models.IntegerField(null=True)),
                ('comment', models.TextField(blank=True, default='Pul chiqimi Client', null=True)),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'CL'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_payee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-out_date'],
            },
        ),
    ]
