# Generated by Django 4.1.6 on 2023-03-05 17:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0015_outcashclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashToCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('date', models.DateTimeField(verbose_name='Sana')),
                ('summa', models.IntegerField(null=True)),
                ('comment', models.TextField(blank=True, default='Kassadan kassaga', null=True)),
                ('in_cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kirim_kassa', to='cashes.cash')),
                ('out_cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chiqim_kassa', to='cashes.cash')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('in_date', models.DateTimeField(verbose_name='Sana')),
                ('summa', models.IntegerField(null=True)),
                ('comment', models.TextField(blank=True, default="Kassa qoldig'i", null=True)),
                ('cash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashes.cash')),
            ],
            options={
                'ordering': ['-in_date'],
            },
        ),
    ]
