# Generated by Django 4.1.6 on 2023-03-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0016_cashtocash_cashbalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashToCash',
        ),
    ]
